"""
Django settings for Django_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
ENV_FILE = PROJECT_ROOT / '.env'


def load_env_file(path):
    """Load simple KEY=VALUE lines from .env without adding a dependency."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


load_env_file(ENV_FILE)


def env(name, default=''):
    return os.environ.get(name, default)


def env_bool(name, default=False):
    value = env(name, str(default)).strip().lower()
    return value in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in env(name, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

# 允许局域网访问与小程序调试
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '*')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'sheep_management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# 切换方式：
#   - 使用云端数据库（默认）：直接运行 python manage.py runserver
#   - 使用本地数据库：设置环境变量后运行
#       Windows PowerShell: $env:USE_LOCAL_DB="1"; python manage.py runserver
#       Windows CMD:        set USE_LOCAL_DB=1 && python manage.py runserver

if env('USE_LOCAL_DB') == '1':
    # ---- 本地数据库 ----
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('LOCAL_DB_NAME', 'sheep_xdb'),
            'USER': env('LOCAL_DB_USER', 'root'),
            'PASSWORD': env('LOCAL_DB_PASSWORD', ''),
            'HOST': env('LOCAL_DB_HOST', '127.0.0.1'),
            'PORT': env('LOCAL_DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # ---- 云端数据库（默认） ----
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('DB_NAME', 'sheep_xdb'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'connect_timeout': int(env('DB_CONNECT_TIMEOUT', '10')),
            },
            # 持久连接：每个 worker 保持连接 600 秒，避免每次请求重新握手
            # 免费 MySQL 延迟高，此项优化效果明显
            'CONN_MAX_AGE': int(env('DB_CONN_MAX_AGE', '600')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (用户上传的文件)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 指定自定义用户模型
AUTH_USER_MODEL = 'sheep_management.User'

# 后台登录 URL（用于 @login_required 装饰器跳转）
LOGIN_URL = '/login/'

# 微信小程序配置
WX_APP_ID = env('WX_APP_ID')
WX_APP_SECRET = env('WX_APP_SECRET')

# DeepSeek 智能问答配置
DEEPSEEK_API_KEY = env('DEEPSEEK_API_KEY')
DEEPSEEK_API_BASE = env('DEEPSEEK_API_BASE', 'https://api.deepseek.com')
DEEPSEEK_MODEL = env('DEEPSEEK_MODEL', 'deepseek-chat')
MOCK_DEEPSEEK = env_bool('MOCK_DEEPSEEK', False)

# Cloudflare R2 配置
R2_ACCOUNT_ID = env('R2_ACCOUNT_ID')
R2_ACCESS_KEY_ID = env('R2_ACCESS_KEY_ID')
R2_SECRET_ACCESS_KEY = env('R2_SECRET_ACCESS_KEY')
R2_BUCKET_NAME = env('R2_BUCKET_NAME')
R2_PUBLIC_URL = env('R2_PUBLIC_URL')

# 覆盖默认的 Media 文件存储以使用 Cloudflare R2 (通过 django-storages S3Boto3 接口)
AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
AWS_S3_ENDPOINT_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_URL.replace('https://', '').replace('http://', '').rstrip('/')
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = None         # R2 默认不支持 ACL
AWS_S3_FILE_OVERWRITE = False  # 同名文件不覆盖会加上后缀

AWS_S3_REGION_NAME = 'auto'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_AUTH = False

# Django 5+ 推荐使用 STORAGES 配置默认文件存储
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# ====================== 生产部署额外配置 ======================

# Cloudflare Tunnel 会把请求通过 127.0.0.1 转发给 Django
# 需要信任来自 Cloudflare 的 X-Forwarded-Proto 头，让 Django 知道原始是 HTTPS
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 如需进一步锁定，将 * 换成你的 Cloudflare Tunnel 域名
# ALLOWED_HOSTS = ['your-domain.com', '127.0.0.1', 'localhost']

