# Generated by Django 6.0.1 on 2026-02-21 09:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="优惠券名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="优惠券代码"),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("discount", "满减券"),
                            ("percentage", "折扣券"),
                            ("cash", "现金券"),
                        ],
                        max_length=20,
                        verbose_name="优惠券类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "可用"),
                            ("inactive", "不可用"),
                            ("expired", "已过期"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="优惠金额（满减券/现金券）",
                    ),
                ),
                (
                    "discount_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="折扣率（折扣券，0-1）"
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低消费金额",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最大折扣金额",
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(blank=True, null=True, verbose_name="总发放数量"),
                ),
                ("used_count", models.IntegerField(default=0, verbose_name="已使用数量")),
                ("user_limit", models.IntegerField(default=1, verbose_name="每用户限领数量")),
                ("valid_from", models.DateTimeField(verbose_name="生效时间")),
                ("valid_until", models.DateTimeField(verbose_name="失效时间")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="使用说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="活动描述"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("flash_sale", "限时抢购"),
                            ("package", "套餐活动"),
                            ("discount", "折扣活动"),
                        ],
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "进行中"),
                            ("ended", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="活动图片"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "discount_rate",
                    models.FloatField(blank=True, null=True, verbose_name="折扣率（0-1）"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="最低消费金额",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最大折扣金额",
                    ),
                ),
                (
                    "total_limit",
                    models.IntegerField(blank=True, null=True, verbose_name="总限购数量"),
                ),
                (
                    "user_limit",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="每用户限购数量"
                    ),
                ),
                ("sold_count", models.IntegerField(default=0, verbose_name="已售数量")),
                (
                    "applicable_sheep_ids",
                    models.TextField(
                        blank=True, null=True, verbose_name="适用羊只ID列表（JSON格式）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "优惠活动",
                "verbose_name_plural": "优惠活动",
                "db_table": "promotion_activities",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="VaccineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="疫苗名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="疫苗描述"),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="生产厂家"
                    ),
                ),
                (
                    "validity_days",
                    models.IntegerField(blank=True, null=True, verbose_name="有效期（天）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "疫苗种类",
                "verbose_name_plural": "疫苗种类",
                "db_table": "vaccine_types",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "普通用户"), (1, "养殖户"), (2, "管理员")],
                        default=0,
                        verbose_name="用户角色",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="养殖户是否审核通过"),
                ),
                (
                    "openid",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="微信openid",
                    ),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="微信unionid"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="头像URL"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "未知"), (1, "男"), (2, "女")],
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Sheep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ear_tag",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="耳标编号"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "母"), (1, "公")], verbose_name="性别"
                    ),
                ),
                ("weight", models.FloatField(verbose_name="体重（kg）")),
                ("height", models.FloatField(verbose_name="身高（cm）")),
                ("length", models.FloatField(verbose_name="体长（cm）")),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="qrcodes/", verbose_name="二维码"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheep_list",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属养殖户",
                    ),
                ),
            ],
            options={
                "verbose_name": "羊只信息",
                "verbose_name_plural": "羊只信息",
                "db_table": "sheep",
            },
        ),
        migrations.CreateModel(
            name="GrowthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField(verbose_name="记录日期")),
                ("weight", models.FloatField(verbose_name="体重（kg）")),
                ("height", models.FloatField(verbose_name="身高（cm）")),
                ("length", models.FloatField(verbose_name="体长（cm）")),
                (
                    "sheep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_records",
                        to="sheep_management.sheep",
                        verbose_name="羊只",
                    ),
                ),
            ],
            options={
                "verbose_name": "生长记录",
                "verbose_name_plural": "生长记录",
                "db_table": "growth_records",
            },
        ),
        migrations.CreateModel(
            name="FeedingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_type", models.CharField(max_length=100, verbose_name="饲料类型")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                ("amount", models.FloatField(verbose_name="数量")),
                ("unit", models.CharField(max_length=20, verbose_name="单位")),
                (
                    "sheep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeding_records",
                        to="sheep_management.sheep",
                        verbose_name="羊只",
                    ),
                ),
            ],
            options={
                "verbose_name": "喂养记录",
                "verbose_name_plural": "喂养记录",
                "db_table": "feeding_records",
            },
        ),
        migrations.CreateModel(
            name="VaccinationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccination_date",
                    models.DateField(db_column="VaccinationDate", verbose_name="接种日期"),
                ),
                (
                    "expiry_date",
                    models.DateField(db_column="ExpiryDate", verbose_name="过期日期"),
                ),
                (
                    "dosage",
                    models.FloatField(db_column="Dosage", verbose_name="剂量（ml）"),
                ),
                (
                    "administered_by",
                    models.CharField(
                        db_column="AdministeredBy", max_length=100, verbose_name="接种人"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="Notes", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "sheep",
                    models.ForeignKey(
                        db_column="sheep_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_records",
                        to="sheep_management.sheep",
                        verbose_name="羊只",
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaccination_records",
                        to="sheep_management.vaccinetype",
                        verbose_name="疫苗种类",
                    ),
                ),
            ],
            options={
                "verbose_name": "疫苗接种记录",
                "verbose_name_plural": "疫苗接种记录",
                "db_table": "vaccinationhistory",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "sheep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="sheep_management.sheep",
                        verbose_name="羊只",
                    ),
                ),
            ],
            options={
                "verbose_name": "购物车商品",
                "verbose_name_plural": "购物车商品",
                "db_table": "cart_items",
                "unique_together": {("user", "sheep")},
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=20,
                        verbose_name="使用状态",
                    ),
                ),
                (
                    "obtained_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "order_id",
                    models.IntegerField(blank=True, null=True, verbose_name="使用的订单ID"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="sheep_management.coupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "user_coupons",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="user_coupon_user_id_eaaee2_idx"
                    ),
                    models.Index(
                        fields=["coupon", "status"],
                        name="user_coupon_coupon__f202a6_idx",
                    ),
                ],
                "unique_together": {("user", "coupon")},
            },
        ),
    ]
