# Generated by Django 5.2.8 on 2025-12-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(max_length=10, verbose_name='性别（男/女）')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('sheep_count', models.IntegerField(verbose_name='羊只总数')),
                ('sheep_id', models.CharField(max_length=50, unique=True, verbose_name='羊只编号')),
                ('female_count', models.IntegerField(verbose_name='母羊数量')),
                ('male_count', models.IntegerField(verbose_name='公羊数量')),
            ],
            options={
                'verbose_name': '养殖户信息',
                'verbose_name_plural': '养殖户信息',
                'db_table': 'breeders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('openid', models.CharField(max_length=128, unique=True, verbose_name='微信openid')),
                ('unionid', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信unionid')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像URL')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='性别（公/母）')),
                ('weight', models.FloatField(verbose_name='体重（kg）')),
                ('height', models.FloatField(verbose_name='身高（cm）')),
                ('length', models.FloatField(verbose_name='体长（cm）')),
                ('breeder', models.ForeignKey(blank=True, db_column='breeder_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheep_list', to='sheep_management.breeder', verbose_name='养殖户')),
            ],
            options={
                'verbose_name': '羊只信息',
                'verbose_name_plural': '羊只信息',
                'db_table': 'sheep',
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('weight', models.FloatField(verbose_name='体重（kg）')),
                ('height', models.FloatField(verbose_name='身高（cm）')),
                ('length', models.FloatField(verbose_name='体长（cm）')),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='sheep_management.sheep', verbose_name='羊只')),
            ],
            options={
                'verbose_name': '生长记录',
                'verbose_name_plural': '生长记录',
                'db_table': 'growth_records',
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=100, verbose_name='饲料类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('amount', models.FloatField(verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='sheep_management.sheep', verbose_name='羊只')),
            ],
            options={
                'verbose_name': '喂养记录',
                'verbose_name_plural': '喂养记录',
                'db_table': 'feeding_records',
            },
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_id', models.IntegerField(choices=[(1, '口蹄疫苗'), (2, '传染性胸膜肺炎灭活疫苗'), (3, '四联苗')], db_column='VaccinationID', verbose_name='疫苗类型ID')),
                ('vaccination_date', models.DateField(db_column='VaccinationDate', verbose_name='接种日期')),
                ('expiry_date', models.DateField(db_column='ExpiryDate', verbose_name='过期日期')),
                ('dosage', models.FloatField(db_column='Dosage', verbose_name='剂量（ml）')),
                ('administered_by', models.CharField(db_column='AdministeredBy', max_length=100, verbose_name='接种人')),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True, verbose_name='备注')),
                ('vaccine_type', models.CharField(blank=True, db_column='VaccineType', max_length=100, null=True, verbose_name='疫苗类型名称')),
                ('sheep', models.ForeignKey(db_column='sheep_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='sheep_management.sheep', verbose_name='羊只')),
            ],
            options={
                'verbose_name': '疫苗接种记录',
                'verbose_name_plural': '疫苗接种记录',
                'db_table': 'vaccinationhistory',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.FloatField(verbose_name='单价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sheep_management.sheep', verbose_name='羊只')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sheep_management.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车商品',
                'verbose_name_plural': '购物车商品',
                'db_table': 'cart_items',
                'unique_together': {('user', 'sheep')},
            },
        ),
    ]
