# Generated by Django 6.0.1 on 2026-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="个人简介"),
        ),
    ]
