# Generated by Django 6.0.1 on 2026-02-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0002_user_birthday_user_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="个人简介"
            ),
        ),
    ]
