# Generated by Django 6.0.1 on 2026-02-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0005_sheep_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheep",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
    ]
