# Generated by Django 6.0.1 on 2026-02-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0006_sheep_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheep",
            name="farm_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="农场名称"
            ),
        ),
    ]
