# Generated by Django 6.0.1 on 2026-02-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0007_sheep_farm_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheep",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="sheep_images/", verbose_name="羊只照片"
            ),
        ),
    ]
