# Generated by Django 6.0.1 on 2026-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0008_sheep_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="账户余额（元）"
            ),
        ),
    ]
