# Generated by Django 6.0.1 on 2026-03-01 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0013_sheep_batch_no_environmentalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheep',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='video',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('role_change', '角色变更'), ('breeder_approved', '养殖户批准'), ('breeder_rejected', '养殖户拒绝'), ('user_created', '用户创建'), ('user_deleted', '用户删除'), ('order_handled', '订单处理'), ('data_modified', '数据修改'), ('other', '其他')], max_length=50, verbose_name='操作类型')),
                ('details', models.TextField(blank=True, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作管理员')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_target_logs', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='audit_logs_admin_i_cd1cac_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx')],
            },
        ),
    ]
