# Generated by Django 6.0.1 on 2026-03-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0014_remove_sheep_batch_no_remove_sheep_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='ear_tag',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='耳标编号'),
        ),
    ]
