# Generated by Django 6.0.1 on 2026-03-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0015_fix_ear_tag_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='ear_tag',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='耳标编号'),
        ),
    ]
