# Generated by Django 6.0.1 on 2026-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0019_knowledgedocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedingrecord",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="feedingrecord",
            name="start_date",
        ),
        migrations.AddField(
            model_name="feedingrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="记录时间"
            ),
        ),
        migrations.AddField(
            model_name="feedingrecord",
            name="feed_date",
            field=models.DateField(default="2000-01-01", verbose_name="喂养日期"),
        ),
    ]
