# Generated by Django 6.0.1 on 2026-05-05 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0032_care_fee_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提现金额')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('bank_name', models.CharField(max_length=100, verbose_name='银行名称')),
                ('bank_card_no', models.CharField(max_length=50, verbose_name='银行卡号')),
                ('account_holder', models.CharField(max_length=50, verbose_name='开户人姓名')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注/拒绝原因')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '提现申请',
                'verbose_name_plural': '提现申请',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='qacategory',
            name='qa_category_sort_i_216b0e_idx',
        ),
        migrations.RenameIndex(
            model_name='qaalias',
            new_name='qa_alias_alias_q_947149_idx',
            old_name='qa_alias_alias_q_3baf30_idx',
        ),
        migrations.RenameIndex(
            model_name='qapair',
            new_name='qa_pair_status_65aea1_idx',
            old_name='qa_pair_status_e90ed6_idx',
        ),
        migrations.RenameIndex(
            model_name='qapair',
            new_name='qa_pair_categor_f8ba70_idx',
            old_name='qa_pair_categor_49235d_idx',
        ),
        migrations.RenameIndex(
            model_name='qapair',
            new_name='qa_pair_is_hot_6e40d5_idx',
            old_name='qa_pair_is_hot_6f2145_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='breeder_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='养殖户应得金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='平台服务费'),
        ),
        migrations.AddField(
            model_name='order',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结算时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_status',
            field=models.CharField(choices=[('pending', '待结算'), ('settled', '已结算')], default='pending', max_length=20, verbose_name='结算状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='breeder_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='养殖户可提现余额（元）'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='养殖户累计收入（元）'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='交付地址'),
        ),
        migrations.AlterField(
            model_name='qalog',
            name='source_type',
            field=models.CharField(choices=[('faq', '问答对'), ('user_data', '用户数据'), ('general', '通用知识')], default='general', max_length=20, verbose_name='数据来源类型'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='breeder',
            field=models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='养殖户'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
