# Generated by Django 6.0.1 on 2026-05-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0033_withdrawal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeDocument',
        ),
    ]
