# Generated by Django 6.0.1 on 2026-05-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0034_delete_knowledgedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
