# Generated by Django 6.0.1 on 2026-05-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0035_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionActivity',
        ),
    ]
