# Generated by Django 6.0.1 on 2026-05-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0036_delete_promotionactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentAlert',
        ),
    ]
